function set_rectangle_coords( obj, minpos, maxpos, spacing )

set( obj.rectangle, 'Position',...
    [minpos(1) minpos(2) maxpos(1)-minpos(1) maxpos(2)-minpos(2) ]+...
    [-0.5 -0.5 1 1]*0.75*spacing );
