Description of get_one_resnum_from_tag
Home > Scripts > setup > get_one_resnum_from_tag.m
get_one_resnum_from_tag
PURPOSE
Convert "A:CQ:1" to 'A','CQ',1
SYNOPSIS
function [resnum,chains,segid,ok] = get_one_resnum_from_tag(tag)
DESCRIPTION
 Convert "A:CQ:1" to 'A','CQ',1
CROSS-REFERENCE INFORMATION
This function calls:
get_resnum_from_tag Convert "A:1-4" to 'AAAA' and [1,2,3,4]
This function is called by:
read_base_pairs
read_base_stacks
read_other_contacts
SOURCE CODE
function [resnum,chains,segid,ok] = get_one_resnum_from_tag(tag)
% Convert "A:CQ:1" to 'A','CQ',1
[resnum,chains,segid,ok] = get_resnum_from_tag(tag);
if ok
    assert( length( resnum ) == 1 );
    assert( length( chains ) == 1 );
    assert( length( segid ) == 1 );
    segid = segid{1};
end