Description of get_domain_tag
get_domain_tag
PURPOSE
tag = get_domain_tag(name);
SYNOPSIS
function tag = get_domain_tag(name);
DESCRIPTION
 tag = get_domain_tag( name );
 Give tag in drawing (gca, current axes of figure) that
  corresponds to tag or name supplied.
 Appropriate converts ' ' and '_' to '-'
 See also: LIST_DOMAINS() to get possible tags.
 (C) R. Das, Stanford University
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
add_residues_to_domain add_residues_to_domain(residue_string, name);
delete_domain delete_domain(name);
remove_residues_from_domain remove_residues_from_domain(residue_string, domain_name);
show_domain_label show_domain_label(name, setting)
SOURCE CODE
function tag = get_domain_tag(name);
% tag = get_domain_tag(name);
%
% Give tag in drawing (gca, current axes of figure) that
%  corresponds to tag or name supplied.
% Appropriate converts ' ' and '_' to '-'
%
% See also: LIST_DOMAINS() to get possible tags.
%
% (C) R. Das, Stanford University
tag = sprintf('Selection_%s_domain', strrep(strrep(name, ' ', '_'),'-','_'));
if ~isappdata(gca, tag);
    tag = sprintf('Selection_%s',strrep(strrep(name, ' ', '_' ),'-','_') );
end
if ~isappdata(gca, tag);
    [~,tag] = get_res( name ); % look inside domain names.
end
if ~isappdata(gca, tag);
    tag = name;
    if ~isappdata( gca, tag )
        fprintf( 'Could not find domain with name: %s\n', name );
    end
end