color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 10
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 11
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 120
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 121
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 121
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 122
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 9
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 10
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 5
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 6
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 126
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 127
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 127
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 128
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 4
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 5
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 67
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 68
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 61
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 62
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 52
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 53
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 78
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 79
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 78
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 79
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 52
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 53
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 26
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 27
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 99
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 100
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 41
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 42
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 88
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 89
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 24
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 25
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 103
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 104
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 27
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 28
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 98
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 99
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 99
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 100
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 26
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 27
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 3
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 4
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 128
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 129
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 129
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 130
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 2
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 3
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 48
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 49
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 81
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 82
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 82
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 83
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 47
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 48
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 103
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 104
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 24
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 25
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 55
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 56
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 73
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 74
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 2
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 3
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 129
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 130
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 58
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 59
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 70
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 71
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 71
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 72
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 57
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 58
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 92
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 93
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 33
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 34
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 56
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 57
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 72
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 73
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 73
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 74
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 55
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 56
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 117
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 118
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 13
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 14
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 42
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 43
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 87
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 88
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 88
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 89
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 41
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 42
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 33
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 34
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 92
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 93
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 93
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 94
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 32
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 33
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 59
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 60
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 69
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 70
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 70
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 71
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 58
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 59
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 46
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 47
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 83
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 84
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 84
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 85
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 45
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 46
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 81
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 82
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 48
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 49
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 4
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 5
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 127
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 128
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 128
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 129
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 3
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 4
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 31
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 32
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 94
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 95
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 95
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 96
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 30
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 31
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 12
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 13
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 118
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 119
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 119
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 120
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 11
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 12
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 29
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 30
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 96
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 97
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 97
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 98
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 28
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 29
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 32
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 33
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 93
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 94
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 94
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 95
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 31
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 32
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 43
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 44
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 86
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 87
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 87
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 88
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 42
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 43
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 44
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 45
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 85
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 86
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 86
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 87
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 43
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 44
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 47
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 48
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 82
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 83
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 83
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 84
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 46
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 47
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 61
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 62
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 67
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 68
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 68
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 69
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 60
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 61
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 13
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 14
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 117
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 118
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 118
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 119
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 12
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 13
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 30
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 31
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 95
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 96
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 96
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 97
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 29
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 30
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 45
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 46
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 84
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 85
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 85
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 86
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 44
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 45
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 60
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 61
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 68
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 69
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 69
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 70
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 59
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 60
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 57
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 58
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 71
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 72
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 72
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 73
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 56
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 57
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 11
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 12
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 119
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 120
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 120
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 121
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 10
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 11
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 28
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 29
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 97
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 98
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 98
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 99
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 27
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 28
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 9
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 10
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 121
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 122
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 126
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 127
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 5
color gray50, spinach_all_models_all_fits_R4.out.1 and chain A and resi 6
color lightblue, spinach_all_models_all_fits_R4.out.1 and chain A and resi 63
color lightblue, spinach_all_models_all_fits_R4.out.1 and chain A and resi 64
color lightblue, spinach_all_models_all_fits_R4.out.1 and chain A and resi 65
color lightblue, spinach_all_models_all_fits_R4.out.1 and chain A and resi 108
color lightblue, spinach_all_models_all_fits_R4.out.1 and chain A and resi 109
color lightblue, spinach_all_models_all_fits_R4.out.1 and chain A and resi 110
color marine, spinach_all_models_all_fits_R4.out.1 and chain A and resi 122
color marine, spinach_all_models_all_fits_R4.out.1 and chain A and resi 123
color marine, spinach_all_models_all_fits_R4.out.1 and chain A and resi 7
color marine, spinach_all_models_all_fits_R4.out.1 and chain A and resi 9
color gold, spinach_all_models_all_fits_R4.out.1 and chain A and resi 51
color gold, spinach_all_models_all_fits_R4.out.1 and chain A and resi 81
color gold, spinach_all_models_all_fits_R4.out.1 and chain A and resi 49
color gold, spinach_all_models_all_fits_R4.out.1 and chain A and resi 66
color gold, spinach_all_models_all_fits_R4.out.1 and chain A and resi 9
color gold, spinach_all_models_all_fits_R4.out.1 and chain A and resi 122
color sand, spinach_all_models_all_fits_R4.out.1 and chain A and resi 124
color sand, spinach_all_models_all_fits_R4.out.1 and chain A and resi 125
color sand, spinach_all_models_all_fits_R4.out.1 and chain A and resi 126
color sand, spinach_all_models_all_fits_R4.out.1 and chain A and resi 6
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 121
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 122
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 123
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 124
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 125
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 126
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 6
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 7
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 9
color limon, spinach_all_models_all_fits_R4.out.1 and chain A and resi 10
