color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 36
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 37
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 32
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 33
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 19
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 20
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 76
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 18
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 19
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 18
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 19
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 79
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 17
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 18
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 52
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 53
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 59
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 61
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 51
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 52
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 76
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 19
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 20
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 17
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 18
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 79
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 79
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 80
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 16
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 17
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 46
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 65
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 66
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 66
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 67
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 44
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 127
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 128
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 150
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 151
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 151
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 152
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 126
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 127
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 134
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 135
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 142
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 143
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 143
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 144
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 133
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 134
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 93
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 94
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 168
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 169
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 169
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 170
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 92
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 93
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 5
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 6
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 87
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 89
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 4
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 5
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 103
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 104
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 116
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 117
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 4
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 5
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 89
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 150
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 151
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 127
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 128
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 87
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 5
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 6
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 94
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 95
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 167
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 168
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 168
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 169
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 93
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 94
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 120
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 121
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 156
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 157
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 157
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 158
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 119
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 120
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 126
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 127
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 151
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 152
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 59
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 52
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 53
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 166
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 167
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 95
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 96
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 81
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 82
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 82
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 83
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 13
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 133
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 134
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 143
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 144
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 44
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 66
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 67
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 104
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 105
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 116
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 116
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 117
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 103
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 104
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 28
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 29
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 41
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 41
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 42
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 27
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 28
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 16
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 17
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 79
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 80
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 80
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 81
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 16
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 51
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 52
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 61
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 105
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 116
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 104
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 105
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 156
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 157
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 120
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 121
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 92
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 93
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 169
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 170
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 27
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 28
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 41
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 42
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 16
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 80
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 81
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 81
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 82
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 32
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 33
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 36
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 37
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 37
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 38
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 31
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 32
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 119
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 120
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 157
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 158
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 65
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 66
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 46
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 31
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 32
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 37
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 38
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 38
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 39
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 30
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 31
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 29
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 30
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 39
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 41
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 28
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 29
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 113
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 107
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 107
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 113
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 105
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 30
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 31
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 38
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 39
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 39
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 29
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 30
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 95
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 96
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 166
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 167
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 167
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 168
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 94
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 95
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 13
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 82
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 83
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 142
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 143
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 134
color gray50, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 135
color lightblue, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 54
color lightblue, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 55
color lightblue, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 56
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 53
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 54
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 57
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 59
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 128
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 129
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 148
color marine, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 150
color ruby, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 54
color ruby, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 55
color ruby, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 56
color ruby, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 57
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 55
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 168
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 94
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 56
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 167
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 95
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 130
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 19
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 131
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 18
color gold, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color sand, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 153
color sand, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 154
color sand, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 155
color sand, FNKT_gly_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 122
