color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 98
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 99
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 91
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 92
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 52
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 53
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 116
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 21
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 22
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 29
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 30
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 24
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 25
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 70
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 71
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 44
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 61
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 62
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 62
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 63
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 43
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 44
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 48
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 49
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 56
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 57
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 56
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 57
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 48
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 49
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 91
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 92
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 98
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 99
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 99
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 100
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 90
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 91
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 25
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 26
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 69
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 70
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 70
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 71
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 24
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 25
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 39
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 65
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 66
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 46
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 61
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 61
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 62
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 44
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 1
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 2
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 79
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 12
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 13
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 35
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 36
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 36
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 37
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 11
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 12
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 53
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 54
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 116
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 52
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 53
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 113
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 54
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 55
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 11
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 12
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 36
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 37
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 46
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 47
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 59
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 61
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 45
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 46
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 32
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 33
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 16
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 26
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 27
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 68
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 69
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 69
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 70
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 25
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 26
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 13
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 34
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 35
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 35
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 36
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 12
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 13
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 76
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 3
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 4
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 29
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 30
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 21
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 22
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 90
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 91
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 99
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 100
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 100
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 101
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 89
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 90
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 105
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 84
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 85
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 89
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 90
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 100
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 101
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 101
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 102
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 89
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 82
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 83
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 107
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 108
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 41
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 64
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 65
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 65
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 66
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 39
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 16
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 32
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 33
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 33
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 34
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 67
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 68
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 27
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 28
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 54
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 55
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 113
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 114
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 115
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 53
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 54
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 27
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 28
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 67
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 68
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 68
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 69
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 26
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 27
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 2
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 3
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 79
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 1
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 2
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 3
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 4
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 76
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 77
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 78
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 2
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 3
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 89
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 101
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 102
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 102
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 103
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 87
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 15
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 33
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 34
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 34
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 35
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 13
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 14
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 87
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 88
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 102
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 103
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 64
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 65
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 40
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 41
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 84
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 85
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 105
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 107
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 83
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 84
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 83
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 84
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 106
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 107
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 107
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 108
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 82
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 83
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 59
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 60
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 46
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 47
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 43
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 44
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 62
color gray50, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 63
color marine, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 71
color marine, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 72
color marine, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 73
color marine, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 24
color sand, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 74
color sand, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 75
color sand, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 76
color sand, SAMIV_SAM_all_models_all_fits_FINAL_R3_half1.out.1 and chain A and resi 4
