color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 19
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 20
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 117
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 118
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 118
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 119
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 18
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 19
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 23
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 24
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 113
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 114
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 114
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 115
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 22
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 23
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 3
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 4
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 134
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 135
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 29
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 30
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 107
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 108
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 108
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 109
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 28
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 29
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 4
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 5
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 133
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 134
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 134
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 135
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 3
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 4
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 58
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 59
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 88
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 89
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 89
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 90
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 57
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 58
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 22
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 23
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 114
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 115
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 115
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 116
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 21
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 22
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 39
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 40
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 102
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 103
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 65
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 66
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 81
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 82
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 82
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 83
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 64
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 65
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 60
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 61
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 86
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 87
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 87
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 88
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 59
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 60
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 67
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 68
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 79
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 80
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 80
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 81
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 66
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 67
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 11
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 12
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 125
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 126
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 57
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 58
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 89
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 90
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 14
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 15
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 122
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 123
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 123
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 124
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 13
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 14
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 43
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 44
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 98
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 99
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 99
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 100
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 42
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 43
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 30
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 31
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 106
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 107
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 107
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 108
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 29
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 30
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 48
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 49
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 93
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 94
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 94
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 95
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 47
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 48
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 93
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 94
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 48
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 49
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 106
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 107
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 30
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 31
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 25
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 26
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 111
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 112
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 112
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 113
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 24
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 25
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 41
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 42
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 100
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 101
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 101
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 102
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 40
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 41
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 12
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 13
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 124
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 125
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 125
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 126
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 11
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 12
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 15
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 16
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 121
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 122
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 122
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 123
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 14
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 15
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 76
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 77
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 70
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 71
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 47
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 48
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 94
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 95
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 95
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 96
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 46
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 47
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 26
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 27
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 110
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 111
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 111
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 112
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 25
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 26
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 6
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 7
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 131
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 132
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 132
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 133
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 5
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 6
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 45
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 46
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 96
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 97
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 97
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 98
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 44
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 45
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 27
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 28
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 109
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 110
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 110
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 111
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 26
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 27
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 64
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 65
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 82
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 83
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 83
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 84
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 63
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 64
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 24
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 25
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 112
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 113
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 113
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 114
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 23
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 24
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 18
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 19
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 118
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 119
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 119
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 120
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 17
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 18
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 21
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 22
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 115
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 116
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 116
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 117
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 20
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 21
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 86
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 87
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 60
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 61
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 40
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 41
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 101
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 102
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 102
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 103
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 39
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 40
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 5
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 6
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 132
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 133
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 133
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 134
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 4
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 5
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 44
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 45
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 97
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 98
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 98
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 99
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 43
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 44
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 68
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 69
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 78
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 79
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 79
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 80
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 67
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 68
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 66
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 67
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 80
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 81
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 81
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 82
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 65
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 66
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 7
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 8
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 130
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 131
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 131
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 132
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 6
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 7
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 17
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 18
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 119
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 120
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 120
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 121
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 16
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 17
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 46
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 47
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 95
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 96
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 96
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 97
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 45
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 46
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 13
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 14
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 123
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 124
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 124
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 125
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 12
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 13
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 59
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 60
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 87
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 88
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 88
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 89
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 58
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 59
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 63
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 64
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 83
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 84
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 69
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 70
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 77
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 78
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 78
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 79
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 68
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 69
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 28
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 29
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 108
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 109
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 109
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 110
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 27
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 28
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 130
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 131
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 7
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 8
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 42
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 43
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 99
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 100
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 100
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 101
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 41
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 42
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 16
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 17
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 120
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 121
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 121
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 122
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 15
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 16
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 20
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 21
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 116
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 117
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 117
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 118
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 19
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 20
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 70
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 71
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 76
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 77
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 77
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 78
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 69
color gray50, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 70
color lightblue, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 2
color lightblue, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 3
color lightblue, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 4
color lightblue, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 72
color lightblue, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 73
color lightblue, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 74
color ruby, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 72
color ruby, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 73
color ruby, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 74
color ruby, eterna3D_all_models_all_fits_R5.out.2 and chain A and resi 75
