Description of get_plot_settings
get_plot_settings
PURPOSE
SYNOPSIS
function plot_settings = get_plot_settings();
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
set_default_theme
set_line_color
set_symbol_color
SOURCE CODE
function plot_settings = get_plot_settings();
plot_settings = getappdata(gca, 'plot_settings');