Description of hide_images
hide_images
PURPOSE
hide_images()
SYNOPSIS
function hide_images()
DESCRIPTION
 hide_images()
 Hide image silhouettes
 (C) R. Das, Stanford University, 2018
CROSS-REFERENCE INFORMATION
This function calls:
show_images show_images(setting);
This function is called by:
show_images_as_boundaries show_images_as_boundaries();
show_images_as_rounded_rectangles show_images_as_rounded_rectangles();
SOURCE CODE
function hide_images()
% hide_images()
%
% Hide image silhouettes
%
% (C) R. Das, Stanford University, 2018
show_images(0);