color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 10
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 11
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 120
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 121
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 121
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 122
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 9
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 10
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 5
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 6
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 126
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 127
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 127
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 128
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 4
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 5
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 63
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 64
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 57
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 58
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 49
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 50
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 71
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 72
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 38
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 39
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 92
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 93
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 2
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 3
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 129
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 130
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 3
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 4
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 128
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 129
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 129
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 130
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 2
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 3
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 22
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 23
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 105
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 106
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 106
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 107
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 21
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 22
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 52
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 53
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 68
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 69
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 69
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 70
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 51
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 52
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 31
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 32
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 96
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 97
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 97
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 98
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 30
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 31
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 55
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 56
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 65
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 66
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 66
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 67
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 54
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 55
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 45
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 46
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 85
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 86
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 86
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 87
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 44
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 45
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 24
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 25
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 103
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 104
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 104
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 105
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 23
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 24
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 21
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 22
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 106
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 107
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 11
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 12
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 119
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 120
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 120
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 121
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 10
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 11
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 112
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 113
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 18
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 19
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 18
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 19
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 112
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 113
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 113
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 114
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 17
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 18
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 27
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 28
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 100
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 101
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 101
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 102
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 26
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 27
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 39
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 40
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 91
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 92
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 92
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 93
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 38
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 39
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 15
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 16
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 115
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 116
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 116
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 117
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 14
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 15
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 44
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 45
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 86
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 87
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 87
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 88
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 43
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 44
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 84
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 85
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 46
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 47
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 14
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 15
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 116
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 117
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 117
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 118
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 13
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 14
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 28
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 29
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 99
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 100
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 100
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 101
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 27
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 28
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 53
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 54
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 67
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 68
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 68
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 69
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 52
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 53
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 13
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 14
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 117
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 118
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 118
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 119
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 12
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 13
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 96
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 97
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 31
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 32
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 42
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 43
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 88
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 89
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 89
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 90
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 41
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 42
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 46
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 47
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 84
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 85
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 85
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 86
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 45
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 46
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 4
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 5
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 127
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 128
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 128
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 129
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 3
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 4
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 40
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 41
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 90
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 91
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 91
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 92
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 39
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 40
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 51
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 52
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 69
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 70
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 70
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 71
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 50
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 51
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 30
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 31
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 97
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 98
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 98
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 99
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 29
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 30
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 50
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 51
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 70
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 71
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 71
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 72
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 49
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 50
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 56
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 57
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 64
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 65
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 65
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 66
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 55
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 56
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 43
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 44
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 87
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 88
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 88
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 89
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 42
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 43
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 17
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 18
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 113
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 114
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 114
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 115
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 16
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 17
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 23
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 24
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 104
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 105
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 105
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 106
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 22
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 23
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 26
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 27
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 101
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 102
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 102
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 103
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 25
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 26
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 57
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 58
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 63
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 64
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 64
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 65
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 56
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 57
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 54
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 55
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 66
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 67
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 67
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 68
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 53
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 54
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 16
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 17
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 114
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 115
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 115
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 116
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 15
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 16
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 41
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 42
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 89
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 90
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 90
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 91
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 40
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 41
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 29
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 30
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 98
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 99
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 99
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 100
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 28
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 29
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 12
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 13
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 118
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 119
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 119
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 120
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 11
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 12
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 25
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 26
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 102
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 103
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 103
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 104
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 24
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 25
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 9
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 10
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 121
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 122
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 126
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 127
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 5
color gray50, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 6
color lightblue, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 33
color lightblue, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 34
color lightblue, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 35
color lightblue, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 59
color lightblue, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 60
color lightblue, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 61
color marine, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 122
color marine, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 123
color marine, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 7
color marine, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 9
color gold, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 62
color gold, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 9
color gold, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 122
color sand, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 124
color sand, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 125
color sand, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 126
color sand, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 6
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 121
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 122
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 123
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 124
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 125
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 126
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 6
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 7
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 9
color limon, ATP_stab_AMP_all_models_all_fits_FINAL_R2.out.1 and chain A and resi 10
