color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 179
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 180
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 208
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 209
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 209
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 210
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 178
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 179
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 148
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 149
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 224
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 225
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 225
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 226
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 147
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 148
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 188
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 189
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 198
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 199
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 199
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 200
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 187
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 188
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 190
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 191
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 196
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 197
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 197
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 198
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 189
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 190
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 157
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 158
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 167
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 168
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 168
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 169
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 156
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 157
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 146
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 147
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 226
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 227
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 227
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 228
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 145
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 146
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 147
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 148
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 225
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 226
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 226
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 227
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 146
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 147
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 156
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 157
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 168
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 169
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 166
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 167
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 158
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 159
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 171
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 172
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 215
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 216
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 208
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 209
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 179
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 180
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 158
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 159
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 166
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 167
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 167
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 168
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 157
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 158
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 185
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 186
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 201
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 202
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 202
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 203
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 184
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 185
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 172
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 173
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 214
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 215
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 215
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 216
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 171
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 172
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 224
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 225
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 148
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 149
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 178
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 179
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 209
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 210
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 35
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 36
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 49
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 50
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 91
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 92
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 120
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 121
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 2
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 3
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 141
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 142
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 122
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 123
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 88
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 89
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 101
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 102
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 110
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 111
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 111
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 112
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 100
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 101
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 214
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 215
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 172
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 173
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 13
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 14
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 133
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 134
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 134
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 135
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 12
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 13
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 65
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 66
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 85
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 86
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 86
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 87
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 64
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 65
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 3
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 4
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 140
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 141
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 141
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 142
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 2
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 3
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 25
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 26
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 61
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 62
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 144
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 145
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 228
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 229
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 27
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 28
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 59
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 60
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 60
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 61
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 26
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 27
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 88
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 89
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 122
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 123
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 100
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 101
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 111
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 112
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 85
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 86
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 65
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 66
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 92
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 93
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 119
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 120
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 120
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 121
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 91
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 92
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 102
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 103
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 109
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 110
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 110
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 111
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 101
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 102
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 140
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 141
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 3
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 4
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 28
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 29
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 58
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 59
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 59
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 60
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 27
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 28
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 116
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 117
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 95
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 96
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 129
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 130
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 17
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 18
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 37
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 38
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 47
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 48
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 48
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 49
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 36
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 37
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 26
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 27
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 60
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 61
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 61
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 62
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 25
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 26
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 79
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 80
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 72
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 73
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 14
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 15
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 132
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 133
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 133
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 134
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 13
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 14
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 189
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 190
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 197
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 198
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 198
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 199
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 188
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 189
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 16
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 17
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 130
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 131
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 131
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 132
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 15
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 16
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 38
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 39
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 46
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 47
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 47
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 48
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 37
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 38
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 56
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 57
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 30
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 31
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 46
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 47
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 38
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 39
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 94
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 95
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 117
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 118
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 118
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 119
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 93
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 94
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 95
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 96
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 116
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 117
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 117
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 118
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 94
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 95
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 72
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 73
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 79
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 80
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 80
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 81
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 71
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 72
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 17
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 18
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 129
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 130
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 130
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 131
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 16
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 17
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 12
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 13
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 134
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 135
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 135
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 136
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 11
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 12
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 71
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 72
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 80
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 81
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 81
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 82
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 70
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 71
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 36
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 37
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 48
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 49
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 49
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 50
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 35
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 36
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 93
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 94
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 118
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 119
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 119
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 120
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 92
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 93
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 30
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 31
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 56
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 57
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 57
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 58
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 29
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 30
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 109
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 110
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 102
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 103
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 186
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 187
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 200
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 201
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 201
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 202
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 185
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 186
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 187
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 188
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 199
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 200
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 200
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 201
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 186
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 187
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 145
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 146
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 227
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 228
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 228
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 229
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 144
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 145
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 196
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 197
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 190
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 191
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 184
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 185
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 202
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 203
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 11
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 12
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 135
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 136
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 70
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 71
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 81
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 82
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 64
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 65
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 86
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 87
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 15
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 16
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 131
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 132
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 132
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 133
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 14
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 15
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 29
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 30
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 57
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 58
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 58
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 59
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 28
color gray50, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 29
color marine, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 180
color marine, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 181
color marine, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 206
color marine, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 208
color gold, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 182
color gold, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 17
color gold, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 130
color gold, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 205
color gold, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 130
color gold, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 17
color sand, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 211
color sand, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 212
color sand, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 213
color sand, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 174
color purple, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 9
color purple, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 11
color purple, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 136
color purple, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 137
color purple, VCKT_gly_all_models_all_fits_FINAL_R4.out.1 and chain A and resi 138
