Description of add_linker_to_residue
Home > Scripts > linkers > add_linker_to_residue.m
add_linker_to_residue
PURPOSE
add_linker_to_residue(res_tag, linker)
SYNOPSIS
function add_linker_to_residue(res_tag, linker_tag)
DESCRIPTION
 add_linker_to_residue( res_tag, linker )
 util function for associating linker information to residues.
 (C) R. Das, Stanford University, 2017
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
delete_tertiary_contact delete_tertiary_contact(contact_name)
setup_arrow_linkers setup_arrow_linkers(resnum,chains)
setup_base_pair_linkers draw_dummy_base_pairs(base_pairs)
setup_basic_linkers setup_basic_linkers(basics)
setup_tertiary_contact setup_tertiary_contact(contact_name, res_tags1, res_tags2)
SOURCE CODE
function add_linker_to_residue(res_tag, linker_tag)
% add_linker_to_residue(res_tag, linker)
% util function for associating linker information to residues.
% (C) R. Das, Stanford University, 2017
residue = getappdata(gca, res_tag);
if ~isfield(residue, 'linkers') residue.linkers = {}; end;
if ~any(strcmp(residue.linkers, linker_tag))
    residue.linkers = [ residue.linkers, linker_tag ];
    setappdata( gca, res_tag, residue );
end