color gold, 3bo3_RNA_altB and chain B and resi 22
color gold, 3bo3_RNA_altB and chain B and resi 169
color gold, 3bo3_RNA_altB and chain B and resi 153
color gold, 3bo3_RNA_altB and chain B and resi 44
color gold, 3bo3_RNA_altB and chain B and resi 92
color gold, 3bo3_RNA_altB and chain B and resi 128
color gold, 3bo3_RNA_altB and chain B and resi 54
color gold, 3bo3_RNA_altB and chain B and resi 6
color gold, 3bo3_RNA_altB and chain D and resi 214
color gold, 3bo3_RNA_altB and chain B and resi 93
color gold, 3bo3_RNA_altB and chain B and resi 42
color gold, 3bo3_RNA_altB and chain B and resi 144
color gold, 3bo3_RNA_altB and chain B and resi 173
color gold, 3bo3_RNA_altB and chain B and resi 9
color gold, 3bo3_RNA_altB and chain B and resi 33
color gold, 3bo3_RNA_altB and chain C and resi 197
color gold, 3bo3_RNA_altB and chain B and resi 79
color gold, 3bo3_RNA_altB and chain B and resi 57
